#!/bin/bash
###########################################################################
# Splunk install script                                                   #
#                                                                         #
#       - This script will install and enable Splunk on boot              #
#       - Create File ACLS for Splunk to access logs while running as     #
#         a protected user account                                        #
#                                                                         #
#       - Created by chris at uconn dot edu 6-27-2019                     #
#       - Updated 4-15-2020 - Updated Splunk RPM                          #
###########################################################################

SPLUNK_FILE="splunkforwarder-8.0.3-a6754d8441bf-linux-2.6-x86_64.rpm"

#######################################
# Make sure network tools and VMware  #
# tools are installed on this host    #
# because we want ALL THE LOGS (XtoY) #
#######################################
yum -y install net-tools open-vm-tools

wget -O $SPLUNK_FILE 'https://download.splunk.com/products/universalforwarder/releases/8.0.3/linux/$SPLUNK_FILE'
wget -O $SPLUNK_FILE.md5 'https://download.splunk.com/products/universalforwarder/releases/8.0.3/linux/$SPLUNK_FILE.md5'


#######################################################################################
# Run a comparison of the file downloaded to what Splunk thinks the MD5 sum should be #
# this way we are most likely not installing something hacked                         #
#######################################################################################
if md5sum --status -c $SPLUNK_FILE.md5; then
	echo "MD5 verification successful, now installing Splunk"
	rpm -ivh $SPLUNK_FILE
else
	echo "There was a MD5 verification failure"
fi

#############################################
# Complete the last of the installation     #
# so that the agent is completely installed #
#############################################
/opt/splunkforwarder/bin/splunk enable boot-start --accept-license --answer-yes --auto-ports --no-prompt


##############################################
# Make sure the Splunk user account actually #
# exists. If not then create it!             #
##############################################
getent passwd splunk > /dev/null 2&>1

if [ $? -eq 0 ]; then
    echo "Yay, the Splunk user account already exists"
else
    echo "No, the user does not exist"
	useradd -d /opt/splunkforwarder/
fi


###################################################################################
# Make changes to the systemd service file for splunk. This will add the User=    #
# option so the service file. This will make splunk start as the user, splunk.    #
#                                                                                 #
# We also need to make sure that Splunk owns everything in its home directory.    #
###################################################################################
echo "#This unit file replaces the traditional start-up script for systemd
#configurations, and is used when enabling boot-start for Splunk on
#systemd-based Linux distributions.

[Unit]
Description=Systemd service file for Splunk, generated by 'splunk enable boot-start'
After=network.target

[Service]
Type=simple
Restart=always
ExecStart=/opt/splunkforwarder/bin/splunk _internal_launch_under_systemd
LimitNOFILE=65536
SuccessExitStatus=51 52
RestartPreventExitStatus=51
RestartForceExitStatus=52
Delegate=true
MemoryLimit=100G
CPUShares=1024
User=splunk

[Install]
WantedBy=multi-user.target" > /etc/systemd/system/SplunkForwarder.service

chown splunk.splunk /opt/splunkforwarder/* -R 


#################################################################
# Set the configuration for the deployment server so the client #
# will actually start logging to the Splunk indexers            #
#################################################################
echo "[deployment-client]
[target-broker:deploymentServer]
targetUri = splunkdeploy.uits.uconn.edu:8089" > /opt/splunkforwarder/etc/system/local/deploymentclient.conf

#####################################
# Set the file ACLs on the box      #
#####################################
/usr/bin/setfacl -m u:splunk:r /var/log/*
/usr/bin/setfacl -m u:splunk:rx /var/log
/usr/bin/setfacl -d -R -m u:splunk:rx /var/log/


##################################################
# Reload the services with the new Splunk script #
# and make sure the system starts on book time   #
##################################################
systemctl daemon-reload
systemctl enable SplunkForwarder.service
systemctl start SplunkForwarder.service